AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'lib/tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Documentation:
  Enabled: false

LineLength:
  Max: 100
