language: ruby
rvm:
- 2.1
sudo: false
cache: bundler
before_install:
- gem install rubocop
script: rubocop --fail-level=W
notifications:
  email:
  - ogataken@gmail.com
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: dMTd63WSiGfuHaSw2gGt/kgnAdiHoEv+jVEzeQ7djC3SFl4SumlHE1KwtLMR7bYz6+azxH6RtyVADgX98LTTLoVDPOSQCckl0uX/xfzx7zZo+p4eNQftz06HJUj3Xl0B2OPQRxHQjFF5FpFGa2HQV4UWcGMFGsk0l186qzBaXkA=
  app: fish-sause
  on:
    repo: tachikomaio/fish-sause
  run:
    - 'rake db:migrate'
    - restart
    - 'rake cleanup'
